CREATE TABLE EXAM (
  ID          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME        VARCHAR(50)  NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL
);

CREATE TABLE QUESTION (
  ID           INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EXAM_ID      INT          NOT NULL,
  NAME         VARCHAR(250) NOT NULL,
  MULTI_ANSWER BIT          NOT NULL DEFAULT 0
);

ALTER TABLE QUESTION ADD FOREIGN KEY (EXAM_ID) REFERENCES EXAM (ID);

CREATE TABLE ANSWER (
  ID          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  QUESTION_ID INT          NOT NULL,
  NAME        VARCHAR(250) NOT NULL,
  IS_CORRECT  BIT          NOT NULL DEFAULT 0
);
ALTER TABLE ANSWER ADD FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (ID);

CREATE TABLE USERS (
  ID       INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  ENABLED  BIT         NOT NULL DEFAULT 1
);

CREATE TABLE AUTHORITIES (
  ID        INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME  VARCHAR(50) NOT NULL,
  AUTHORITY VARCHAR(50) NOT NULL
);
ALTER TABLE AUTHORITIES ADD FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME);

CREATE TABLE PROTOCOL (
  ID              INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EXAM_ID         INT      NOT NULL,
  USER_ID         INT      NOT NULL,
  START           DATETIME NOT NULL,
  FINISH          DATETIME,
  QUESTION_COUNT  INT,
  CORRECT_ANSWERS INT,
  GRADE           INT
);
ALTER TABLE PROTOCOL ADD FOREIGN KEY (EXAM_ID) REFERENCES EXAM (ID);
ALTER TABLE PROTOCOL ADD FOREIGN KEY (USER_ID) REFERENCES USERS (ID);
